### ISSUE TITLE
Feature request: Add link to comments in RSS feed contents

### ISSUE THREAD

**Issue by Tetracerus** [polyrabbit/hacker-news-digest#14]
The web version shows an icon and count of comments.  Clicking on it takes you to the Hacker News page with all user comments.  However, the RSS feed does not include such a link.  

I would find the RSS feed much more useful if a link to the comments page was added into the content.

**Comment by polyrabbit** [comment]
OK, will implement later.

**Comment by polyrabbit** [comment]
@Tetracerus Just added the comment link to feed. But I'm not sure how your RSS reader handles those two link tags, will it display correctly?
<img width="713" alt="image" src="https://user-images.githubusercontent.com/2657334/196749775-c0a23326-1690-4e66-be4f-95b8b2ff91ae.png">

**Comment by Tetracerus** [comment]
No apparent difference in one RSS reader.  A different RSS reader now ONLY opens to ycombinator and no longer has a way to go directly to the article.  
So I'd say this change is not ideal.

**Comment by polyrabbit** [comment]
OK，so those readers donot fully support RSS standard.
I need to revert this change.

**Comment by Tetracerus** [comment]
Something simpler, like an HTML "Comments" link at the end of each item's contents should be safe.

**Comment by polyrabbit** [comment]
Added, PTAL

**Comment by Tetracerus** [comment]
Appears to work properly.  Thanks
