### ISSUE TITLE
Incomplete news summary

### ISSUE THREAD

**Issue by MstMoonshine** [polyrabbit/hacker-news-digest#19]
For some news, the summary is not shown completely, and there is no link provided to check out the full summary. Is it that the summary does end with an ellipsis or that the summary is not rendered correctly?

Example:

1.
![Example 1](https://github.com/polyrabbit/hacker-news-digest/assets/13410629/4623e0e0-0240-4e01-982a-1409d9deceec)

2.
![Example 2](https://github.com/polyrabbit/hacker-news-digest/assets/13410629/e8f52fc8-9d34-40e9-b790-0d92fb845904)

**Comment by polyrabbit** [comment]
@MstMoonshine It's done on purpose - an ellipsis means the summary is truncated to 400 characters.

Sometimes, OpenAI just returns a long text, making it barely a summary. So I add a soft limit in the prompt and a hard limit in the rendered HTML to keep the page clean.

**Comment by MstMoonshine** [comment]
I see in news.py you make GPT to summarize the content in 2 sentences. Is that the soft limit you mentioned? What about changing the prompt to something like “summarize the content within 200 words.” ?

**Comment by polyrabbit** [comment]
Right, it seems LLM doesnot follow length instruction precisely. I have tried prompt like "xx words / xx characters", and found "2 sentences" is the closest one to my length limitation.

Or do you have any working experience on how to hard limit the length in the prompt?

**Comment by polyrabbit** [comment]
@MstMoonshine Hi, just added a simple and quick solution - full summary can be seen from the tooltips, if it's truncated on the page. Hope it helps.

<img width="888" alt="image" src="https://github.com/polyrabbit/hacker-news-digest/assets/2657334/6c348992-d9b6-4190-874c-9ffa9cc75bba">

**Comment by MstMoonshine** [comment]
That certainly helps! But that leads to another problem. 

I use an RSS reader for your website. The RSS reader preview shows the truncated version. So if I want to read the full version, I have to go for the webpage. That is fine. But the problem is, there is currently no link to your page in the RSS feed! (Currently, there is one link for the news website and another for the HN comment)
As a result, I have to find your website manually and search for the article of interest manually then hover the mouse over the paragraph.

Consider adding a link to the RSS feed, which links to the corresponding summary paragraph. That definitely helps!

**Comment by polyrabbit** [comment]
OK, for RSS readers, I suppose it's OK to output the full summary. 

But I also find some RSS readers doesnot update content even when the source has updated - this happens a lot when upvotes of a news raises to a certain threshold, and I'll switch to ChatGPT to get a better summary.

For this problem, I added a `[summary]` link in the RSS content to get user back to the webpage.

<img width="688" alt="image" src="https://github.com/polyrabbit/hacker-news-digest/assets/2657334/12abf8de-ac40-4517-b0da-f8afaa51569d">

**Comment by MstMoonshine** [comment]
Great. The project's been a useful daily tool already.
