### ISSUE TITLE
signaling another similar project

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [polyrabbit/hacker-news-digest#23]
Hi, just in case you didn't know there is another website doing something similar. You might be interested in it but it's not open source : https://www.emergentmind.com/

Hope you find this useful.

**Comment by polyrabbit** [comment]
Interesting.. we had the same idea. It seems this website does more than summarize, it allows user to submit a link. Maybe the author wants to build another Hacker News in AI field?
