### ISSUE TITLE
Descriptions in the RSS sometimes don't include [comments] link

### ISSUE THREAD

**Issue by bkewl** [polyrabbit/hacker-news-digest#37]
It seems that the RSS feed.xml doesn't include the [comments] link after [summary].

I think it's when there are 0 comments in the thread, because it seems to show up later.
Here's one I caught in the wild which started with no link:
<img width="1674" alt="image" src="https://github.com/polyrabbit/hacker-news-digest/assets/23626407/84aaaf35-4516-4530-9b98-4d6bafdef29e">

Which had no comments:
<img width="977" alt="image" src="https://github.com/polyrabbit/hacker-news-digest/assets/23626407/c50ecf6e-32d3-44f9-814f-45ada051bd6c">

Then later it had the comments link.
<img width="1654" alt="image" src="https://github.com/polyrabbit/hacker-news-digest/assets/23626407/33e01586-08fa-4d9f-8c3b-1517317c6bf6">

I think this is fine when reading from [the summary page](https://hackernews.betacat.io), but if my reader (Feedly) picks up the item while the description doesn't have [comments] I never see it and have to manually navigate to the thread to see if any comments have appeared. For the RSS feed, maybe it just makes sense to always render the comments link here?https://github.com/polyrabbit/hacker-news-digest/blob/e938b54b1e3adec47b2121c5da64d07aca0e44ff/publish.py#L112 

Thanks for making this public, by the way. It's my favourite feed!

**Comment by polyrabbit** [comment]
Thanks for the feedback, now we have links for news with zero comments - https://github.com/polyrabbit/hacker-news-digest/commit/eb874370cad9cba7fdc3611d2b3440a34b810b62

**Comment by bkewl** [comment]
Amazing, thank you!

**Comment by bkewl** [comment]
Amazing, thank you!
