### ISSUE TITLE
Add digest comments?

### ISSUE THREAD

**Issue by brandonJY** [polyrabbit/hacker-news-digest#5]
Hi,

Loved what you have for hack news digest? Is it possible to add a digest comment session in the RSS feed? (to show top comments for each article).

**Comment by polyrabbit** [comment]
Thanks, but it's not on the plan. Currently RSS feed has picture and summary text, there is no space for the additional digest comments, also most  RSS feed readers will mess up the summary text and comments.

**Comment by polyrabbit** [comment]
@brandonJY Hi, a "comments" link is appended to each feed. Not a digest yet but I hope it provides some help. Also see #19
